### ISSUE TITLE
Sanitizer should run on raw markdown not marked output

### ISSUE THREAD

**Issue by styxpilled** [BearToCode/carta-md#6]
Sanitizing the parsed markdown may interfere with things like marked plugins or even basic markdown syntax like images. So the sanitizing should run on the raw input and not the parsed markdown.
Maybe in addition a second option that allows for sanitizing the parsed markdown as well? But I'm not sure in what case someone would need that...

**Comment by BearToCode** [comment]
Hi,
unluckily this is not possible for several reasons:
1. HTML is allowed in markdown by [design](https://spec.commonmark.org/0.29/#raw-html), that means that just removing all HTML tags from the raw markdown does not follow commonmark rules.
2. Even if all raw HTML was removed from the input, there are still [many ways](https://book.hacktricks.xyz/pentesting-web/xss-cross-site-scripting/xss-in-markdown) an XSS attack may be conducted, not including possible flaws in marked in particular.
3. For the previous reason, to my knowledge, there is no raw markdown sanitizer. Also, even if there was one, it should be updated everytime someone creates a new extension with some new syntax that might allow a new exploit. So the safest thing is just to sanitize the raw html output, as it handles all possible cases(which is what all markdown parsers do).

I decided to leave the choice of the sanitizer to the user because custom extensions could render tags/attributes that were not expected in the "vanilla" version. If you are looking for one, I suggest using [DOMPurify](https://github.com/cure53/DOMPurify) if your editor is only running on the client, where you do not have to specify the single allowed tags. Otherwise, if it is expected to also run on the server, I suggest [sanitize-html](https://www.npmjs.com/package/sanitize-html), which is the one I'm currently using. I suggest to copy the default options(in the readme) and to update them as you work on the editor.
